from enum import Enum

class AestheticsEnum(str, Enum):
    VINTAGE = "Vintage Aesthetic"
    MINIMALIST = "Minimalist Aesthetic"
    ACUBI = "Acubi Aesthetic"
    OLD_MONEY = "Old Money Aesthetic"
    MERMAIDCORE = "Mermaidcore Aesthetic"
    COTTAGECORE = "Cottagecore Aesthetic"
    FAIRYCORE = "Fairycore Aesthetic"
    ETHEREAL = "Ethereal Aesthetic"
    SPACECORE = "Spacecore Aesthetic"
    LIGHT_ACADEMIA = "Light Academia Aesthetic"
    DARK_ACADEMIA = "Dark Academia Aesthetic"
    GOTHCORE = "Gothcore Aesthetic"
    BALLETCORE = "Balletcore Aesthetic"
    COQUETTE = "Coquette Aesthetic"
    SKATER = "Skater Aesthetic"
    ART_HOE = "Art Hoe Aesthetic"
    ELEVATED_INDIE = "Elevated Indie Aesthetic"
    CYBERPUNK = "Cyberpunk Aesthetic"
    COASTAL_GRANDMOTHER = "Coastal Grandmother Aesthetic"
    COASTAL_COWGIRL = "Coastal Cowgirl Aesthetic"
    TOMATO_GIRL = "Tomato Girl Aesthetic"
    SOFT_GIRL = "Soft Girl Aesthetic"
    BARBIECORE = "Barbiecore Aesthetic"
    BEIGE = "Beige Aesthetic"
    WHIMSICAL = "Whimsical Aesthetic"
    EARLY_2000S = "Early 2000s Aesthetic"
    Y2K = "Y2K Aesthetic"
    TWEE = "Twee Aesthetic"
    KAWAII = "Kawaii Aesthetic"
    GRUNGE = "Grunge Aesthetic"
    VSCO_GIRL = "VSCO Girl Aesthetic"
    E_GIRL = "E-Girl Aesthetic"
    BADDIE = "Baddie Aesthetic"
    NORMCORE = "Normcore Aesthetic"
    PREPPY = "Preppy Aesthetic"